/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

import Message.Request;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author mbera
 */
public class GroupChat extends javax.swing.JFrame
{
	String ProjectName;
	String ClientName;
	Client client;
	public static DefaultListModel DLMMessageList;
	
	public GroupChat(Client client)
	{
		initComponents();
		this.client = client;
		DLMMessageList = new DefaultListModel();
		MessagesList.setModel(DLMMessageList);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		this.setLocationRelativeTo(null);
	}
	
	public void getMessages()
	{
		Request request = new Request(Request.requestType.GetGroupMessages);
		request.projectName = ProjectName;
		this.client.sendToServer(request);
	}
	
	public void Refresh()
	{
		MessagesList.setModel(DLMMessageList);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessagesList = new javax.swing.JList<>();
        MessageTextField = new javax.swing.JTextField();
        SendMessageButton = new javax.swing.JButton();
        SendFileButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(MessagesList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 400, 230));
        jPanel1.add(MessageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 252, 303, -1));

        SendMessageButton.setText("Send ");
        SendMessageButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SendMessageButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SendMessageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 85, -1));

        SendFileButton.setText("File");
        SendFileButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SendFileButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SendFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 85, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
    private void SendMessageButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SendMessageButtonActionPerformed
    {//GEN-HEADEREND:event_SendMessageButtonActionPerformed
        String message = this.client.clientName + ":" + MessageTextField.getText();
		Refresh();
		Request request = new Request(Request.requestType.SendMessageToGroup);
		request.request = message;
		request.projectName = ProjectName;
		this.client.sendToServer(request);
		MessageTextField.setText("");
    }//GEN-LAST:event_SendMessageButtonActionPerformed

    private void SendFileButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SendFileButtonActionPerformed
    {//GEN-HEADEREND:event_SendFileButtonActionPerformed
        ArrayList<Object> fileArr = new ArrayList<>();
        JFileChooser j = new JFileChooser();
        int dialog = j.showSaveDialog(this);
        if (dialog == JFileChooser.APPROVE_OPTION) {
			try {
				File inputFile = j.getSelectedFile();
				byte[] mybytearray = new byte[(int) inputFile.length()];
				FileInputStream fis = new FileInputStream(inputFile);
				BufferedInputStream bis = new BufferedInputStream(fis);
				bis.read(mybytearray, 0, mybytearray.length);
				fileArr.add(this.ProjectName);
				fileArr.add(inputFile.getName());
				fileArr.add(mybytearray);
				fileArr.add(0);
				fileArr.add(mybytearray.length);
				fileArr.add(this.client.clientName);
				Request msg = new Request(Request.requestType.SendFileToGroup);
				msg.request = fileArr;
				this.client.sendToServer(msg);
			} catch (IOException ex) {
				Logger.getLogger(GroupChat.class.getName()).log(Level.SEVERE, null, ex);
			}

            
        }
    }//GEN-LAST:event_SendFileButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        Request request = new Request(Request.requestType.OutFromProject);
		request.request = this.ProjectName;
		this.client.sendToServer(request);
    }//GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GroupChat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MessageTextField;
    private javax.swing.JList<String> MessagesList;
    private javax.swing.JButton SendFileButton;
    private javax.swing.JButton SendMessageButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
